"""Bounded access to files generated by browser commands."""

from __future__ import annotations

import base64
import json
import re
from pathlib import Path
from typing import Any
from uuid import uuid4

from .errors import BrowserError

MAX_ARTIFACT_TEXT = 12_000
MAX_ARTIFACT_BYTES = 12 * 1024 * 1024
MAX_INLINE_ACTOR_CHARS = 12_000
MAX_SEARCH_HITS = 10
MAX_SEARCH_CHARS = 6_000
TEXT_SUFFIXES = (".yml", ".yaml", ".txt", ".json")
IMAGE_MIME_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
}
_PATH_PATTERN = re.compile(
    r"(?:[A-Za-z]:)?[^\s()<>\"]+\.(?:yml|yaml|txt|json|png|jpe?g|webp)",
    re.IGNORECASE,
)


def extract_paths(value: Any) -> list[str]:
    """Collect unique browser artifact paths from a CLI response."""

    paths: list[str] = []
    if isinstance(value, str):
        paths.extend(match.rstrip(".,;") for match in _PATH_PATTERN.findall(value))
    elif isinstance(value, dict):
        for item in value.values():
            paths.extend(extract_paths(item))
    elif isinstance(value, list):
        for item in value:
            paths.extend(extract_paths(item))
    return list(dict.fromkeys(paths))


class ArtifactStore:
    """Own the browser session and task-evidence filesystem boundaries."""

    def __init__(self, session_root: Path, evidence_root: Path) -> None:
        self.session_root = session_root.resolve()
        self._evidence_root = evidence_root.resolve()

    @property
    def evidence_root(self) -> Path:
        return self._evidence_root

    @evidence_root.setter
    def evidence_root(self, value: Path) -> None:
        path = Path(value).resolve()
        _make_private_directory(path)
        self._evidence_root = path

    def prepare_session(self) -> None:
        _make_private_directory(self.session_root)

    def resolve_read_path(self, value: object) -> Path:
        """Resolve a model-supplied path inside one of the two allowed roots."""

        if not isinstance(value, str) or not value.strip():
            raise BrowserError("invalid_artifact_path", "An artifact path is required")
        raw = Path(value)
        path = (raw if raw.is_absolute() else self.session_root / raw).resolve()
        if not any(
            _is_within(path, root) for root in (self.session_root, self.evidence_root)
        ):
            raise BrowserError(
                "invalid_artifact_path",
                "Artifact path is outside the browser output directories",
            )
        if path.suffix.lower() not in (*TEXT_SUFFIXES, *IMAGE_MIME_TYPES):
            raise BrowserError(
                "invalid_artifact_path",
                "Only CLI snapshot and image artifacts can be read",
            )
        return path

    def rewrite_snapshot_args(self, args: list[str]) -> list[str]:
        rewritten = list(args)
        for index, value in enumerate(rewritten):
            if value == "--filename" and index + 1 < len(rewritten):
                rewritten[index + 1] = str(
                    self._snapshot_output_path(rewritten[index + 1])
                )
            elif value.startswith("--filename="):
                output = self._snapshot_output_path(value.split("=", 1)[1])
                rewritten[index] = f"--filename={output}"
        return rewritten

    def prepare_screenshot(self, args: list[str]) -> tuple[list[str], Path]:
        rewritten = list(args)
        path: Path | None = None
        for index, value in enumerate(rewritten):
            if value == "--filename" and index + 1 < len(rewritten):
                path = self._screenshot_output_path(rewritten[index + 1])
                rewritten[index + 1] = str(path)
            elif value.startswith("--filename="):
                path = self._screenshot_output_path(value.split("=", 1)[1])
                rewritten[index] = f"--filename={path}"
        if path is None:
            _make_private_directory(self.evidence_root)
            path = self.evidence_root / f"screenshot-{uuid4().hex}.png"
            rewritten.append(f"--filename={path}")
        return rewritten, path

    def read(self, args: dict[str, Any]) -> dict[str, Any]:
        path = self.resolve_read_path(args.get("path"))
        offset = args.get("offset", 0)
        if not isinstance(offset, int) or offset < 0 or offset > 1_000_000:
            raise BrowserError(
                "invalid_artifact_offset",
                "Artifact offset must be nonnegative and bounded",
            )
        self._ensure_readable_file(path)
        suffix = path.suffix.lower()
        if suffix in IMAGE_MIME_TYPES:
            data = base64.b64encode(path.read_bytes()).decode("ascii")
            return {
                "status": "read",
                "path": str(path),
                "content": [
                    {
                        "type": "image",
                        "data": data,
                        "mimeType": IMAGE_MIME_TYPES[suffix],
                    }
                ],
            }
        text = path.read_text(encoding="utf-8", errors="replace")
        chunk = text[offset : offset + MAX_ARTIFACT_TEXT]
        end = offset + len(chunk)
        return {
            "status": "read",
            "path": str(path),
            "text": chunk,
            "offset": offset,
            "next_offset": end if end < len(text) else None,
            "truncated": end < len(text),
        }

    def search(self, args: dict[str, Any]) -> dict[str, Any]:
        path = self.resolve_read_path(args.get("path"))
        query = args.get("query")
        if not isinstance(query, str) or not query:
            raise BrowserError(
                "invalid_search_query", "A non-empty literal query is required"
            )
        if len(query) > 2000 or "\x00" in query:
            raise BrowserError("invalid_search_query", "The literal query is too long")
        if path.suffix.lower() not in TEXT_SUFFIXES:
            raise BrowserError(
                "text_artifact_required",
                "Only generated text artifacts can be searched",
            )
        self._ensure_readable_file(path)
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            raise BrowserError(
                "artifact_read_failed",
                "Could not read the browser artifact",
            ) from exc
        return _search_text(path, query, text)

    def compact_for_actor(
        self, command: str, payload: dict[str, Any]
    ) -> dict[str, Any]:
        """Replace oversized inline model output with an explicit artifact handle."""

        if command not in {"snapshot", "find", "eval"}:
            return payload
        value = payload.get("result")
        source: Any = value
        if value is None and command == "snapshot" and "snapshot" in payload:
            source = payload
            value = payload["snapshot"]
        if value is None:
            return payload
        if isinstance(value, str):
            serialized = value
        elif isinstance(value, (dict, list)):
            serialized = json.dumps(source, ensure_ascii=False, indent=0)
        else:
            return payload
        if len(serialized) <= MAX_INLINE_ACTOR_CHARS:
            return payload

        artifact = self._write_text(command, serialized)
        size = len(serialized.encode("utf-8"))
        compact = dict(payload)
        compact["result"] = {
            "artifact": str(artifact),
            "size": size,
            "truncated": True,
            "guidance": (
                "Read with read_browser_artifact using offset, or search with "
                "search_browser_artifact using a literal query."
            ),
        }
        if command == "snapshot":
            compact.pop("snapshot", None)
        compact["artifact_path"] = str(artifact)
        compact["artifact_size"] = size
        return compact

    def snapshot_text(
        self,
        command: str,
        payload: dict[str, Any],
        *,
        fresh_after_ns: int | None = None,
        limit: int,
    ) -> str:
        """Read only snapshot-bearing text files that are fresh for this dispatch."""

        sources: list[Any] = []
        if command == "snapshot":
            sources.append(payload)
        else:
            if "snapshot" in payload:
                sources.append(payload["snapshot"])
            result = payload.get("result")
            if isinstance(result, dict) and "snapshot" in result:
                sources.append(result["snapshot"])
        raw_paths = list(
            dict.fromkeys(path for source in sources for path in extract_paths(source))
        )

        chunks: list[str] = []
        for raw_path in raw_paths:
            try:
                path = self.resolve_read_path(raw_path)
            except BrowserError:
                continue
            if path.suffix.lower() not in TEXT_SUFFIXES or not path.is_file():
                continue
            try:
                if (
                    fresh_after_ns is not None
                    and path.stat().st_mtime_ns <= fresh_after_ns
                ):
                    continue
                text = path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            chunks.append(f"Artifact {path.name}:\n{text[:limit]}")
            if sum(len(chunk) for chunk in chunks) >= limit:
                break
        return "\n\n".join(chunks)[:limit]

    def screenshot_content(self, path: Path) -> list[dict[str, str]]:
        if not path.is_file():
            raise BrowserError(
                "screenshot_missing",
                "The Playwright CLI did not create the requested screenshot",
            )
        suffix = path.suffix.lower()
        return [
            {
                "type": "image",
                "data": base64.b64encode(path.read_bytes()).decode("ascii"),
                "mimeType": IMAGE_MIME_TYPES.get(suffix, "image/png"),
            }
        ]

    def _snapshot_output_path(self, value: str) -> Path:
        raw = Path(value)
        path = (raw if raw.is_absolute() else self.session_root / raw).resolve()
        if not _is_within(path, self.session_root):
            raise BrowserError(
                "invalid_artifact_path",
                "Snapshot output must stay in the browser session directory",
            )
        if path.suffix.lower() not in TEXT_SUFFIXES:
            raise BrowserError(
                "invalid_artifact_path",
                "Snapshot output must be a text artifact",
            )
        _make_private_directory(path.parent)
        return path

    def _screenshot_output_path(self, value: str) -> Path:
        raw = Path(value)
        path = (raw if raw.is_absolute() else self.evidence_root / raw).resolve()
        if not _is_within(path, self.evidence_root):
            raise BrowserError(
                "invalid_artifact_path",
                "Screenshot output must stay in the task evidence directory",
            )
        return path

    def _write_text(self, command: str, text: str) -> Path:
        self.prepare_session()
        safe_command = re.sub(r"[^a-zA-Z0-9_.-]", "_", command)[:40] or "browser"
        path = self.session_root / f"{safe_command}-{uuid4().hex}.txt"
        try:
            path.write_text(text, encoding="utf-8")
            path.chmod(0o600)
        except OSError as exc:
            raise BrowserError(
                "artifact_write_failed",
                "Could not save the browser result artifact",
                uncertain=True,
            ) from exc
        return path

    @staticmethod
    def _ensure_readable_file(path: Path) -> None:
        if not path.is_file():
            raise BrowserError(
                "artifact_not_found",
                "The requested browser artifact does not exist",
            )
        try:
            size = path.stat().st_size
        except OSError as exc:
            raise BrowserError(
                "artifact_read_failed",
                "Could not inspect the browser artifact",
            ) from exc
        if size > MAX_ARTIFACT_BYTES:
            raise BrowserError(
                "artifact_too_large",
                "The requested browser artifact is too large",
            )


def _search_text(path: Path, query: str, text: str) -> dict[str, Any]:
    lines = text.splitlines(keepends=True)
    line_starts: list[int] = []
    cursor = 0
    for line in lines:
        line_starts.append(cursor)
        cursor += len(line)

    matches: list[dict[str, Any]] = []
    total = 0
    excerpt_chars = 0
    truncated = False
    pattern = re.compile(re.escape(query), flags=re.IGNORECASE)
    for line_index, raw_line in enumerate(lines):
        line = raw_line.rstrip("\r\n")
        match = pattern.search(line)
        if match is None:
            continue
        total += 1
        if len(matches) >= MAX_SEARCH_HITS or excerpt_chars >= MAX_SEARCH_CHARS:
            truncated = True
            continue

        remaining = MAX_SEARCH_CHARS - excerpt_chars
        context_start_line = max(0, line_index - 1)
        context_end_line = min(len(lines), line_index + 2)
        context = "".join(lines[context_start_line:context_end_line]).rstrip("\r\n")
        target_offset = (
            line_starts[line_index] - line_starts[context_start_line] + match.start()
        )
        if len(context) > remaining:
            excerpt_start = max(0, target_offset - remaining // 2)
            if excerpt_start + remaining > len(context):
                excerpt_start = max(0, len(context) - remaining)
            context = context[excerpt_start : excerpt_start + remaining]
            truncated = True
        matches.append(
            {
                "line": line_index + 1,
                "offset": line_starts[line_index] + match.start(),
                "text": context,
            }
        )
        excerpt_chars += len(context)

    if total > len(matches):
        truncated = True
    return {
        "status": "searched",
        "path": str(path),
        "query": query,
        "matches": matches,
        "count": total,
        "truncated": truncated,
    }


def _make_private_directory(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True, mode=0o700)
    try:
        path.chmod(0o700)
    except OSError:
        pass


def _is_within(path: Path, root: Path) -> bool:
    return path == root or root in path.parents
